In [2]:
import numpy as np
import pandas as pd

from plotly.graph_objs import Scatter, Layout

from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
import plotly.graph_objs as go

init_notebook_mode(connected=True)

import cufflinks as cf
cf.go_offline()

In [3]:
uscars=pd.read_excel('uscars.xlsx')

In [3]:
uscars.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Jusidiction,2015 Households Without Vehicles,2016 Households Without Vehicles,2015 Vehicles per Household,2016 Vehicles per Household
0,Source:,NaN,NaN,"Abilene, Texas",0.054,0.080,1.71,1.69
1,http://www.governing.com/gov-data,NaN,NaN,"Akron, Ohio",0.145,0.129,1.42,1.46
2,NaN,NaN,NaN,"Albuquerque, New Mexico",0.085,0.069,1.69,1.75
3,NaN,NaN,NaN,"Alexandria, Virginia",0.101,0.100,1.38,1.34
4,NaN,NaN,NaN,"Allentown, Pennsylvania",0.192,0.169,1.31,1.33

In [4]:
uscars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 317 entries, 0 to 316
Data columns (total 8 columns):
Unnamed: 0                          2 non-null object
Unnamed: 1                          0 non-null float64
Unnamed: 2                          0 non-null float64
Jusidiction                         317 non-null object
2015 Households Without Vehicles    317 non-null float64
2016 Households Without Vehicles    317 non-null float64
2015 Vehicles per Household         317 non-null float64
2016 Vehicles per Household         317 non-null float64
dtypes: float64(6), object(2)
memory usage: 19.9+ KB

In [5]:
uscars.describe()

,Unnamed: 1,Unnamed: 2,2015 Households Without Vehicles,2016 Households Without Vehicles,2015 Vehicles per Household,2016 Vehicles per Household
count,0.0,0.0,317.000000,317.000000,317.000000,317.000000
mean,NaN,NaN,0.096959,0.093038,1.691041,1.715363
std,NaN,NaN,0.073311,0.074166,0.291922,0.298963
min,NaN,NaN,0.010000,0.007000,0.630000,0.630000
25%,NaN,NaN,0.053000,0.049000,1.540000,1.550000
50%,NaN,NaN,0.078000,0.073000,1.680000,1.720000
75%,NaN,NaN,0.112000,0.109000,1.880000,1.910000
max,NaN,NaN,0.545000,0.544000,2.390000,2.360000

## Task 1:

**Create a Pareto chart of the top 10 states with the highest average number of vehicles per household in 2016.**

In [4]:
df=uscars[['Jusidiction','2016 Vehicles per Household']]
df.head(5)

               Jusidiction  2016 Vehicles per Household
0           Abilene, Texas                         1.69
1              Akron, Ohio                         1.46
2  Albuquerque, New Mexico                         1.75
3     Alexandria, Virginia                         1.34
4  Allentown, Pennsylvania                         1.33

In [5]:
df['states']=df['Jusidiction'].apply(lambda s:s.split(',')[-1])
df.head(10)

               Jusidiction  2016 Vehicles per Household         states
0           Abilene, Texas                         1.69          Texas
1              Akron, Ohio                         1.46           Ohio
2  Albuquerque, New Mexico                         1.75     New Mexico
3     Alexandria, Virginia                         1.34       Virginia
4  Allentown, Pennsylvania                         1.33   Pennsylvania
5          Amarillo, Texas                         1.81          Texas
6      Anaheim, California                         2.05     California
7        Anchorage, Alaska                         1.95         Alaska
8      Ann Arbor, Michigan                         1.44       Michigan
9      Antioch, California                         2.24     California

In [6]:
df_1=df.groupby('states').mean().sort_values(by='2016 Vehicles per Household',ascending=False).head(10)
df_1['percentage']=df_1['2016 Vehicles per Household'].cumsum()/df_1["2016 Vehicles per Household"].sum()*100

df_1.reset_index(inplace=True)
df_1.head(10)

          states  2016 Vehicles per Household  percentage
0           Utah                     2.047500   10.894524
1     California                     1.960667   21.327016
2         Alaska                     1.950000   31.702753
3        Montana                     1.910000   41.865654
4       Colorado                     1.895385   51.950789
5       Oklahoma                     1.827500   61.674716
6          Texas                     1.821795   71.368287
7   South Dakota                     1.820000   81.052308
8        Arizona                     1.781000   90.528815
9         Kansas                     1.780000  100.000000

In [7]:
trace0 = go.Bar(
    x=df_1['states'],
    y=df_1['2016 Vehicles per Household'],
    text=df_1['2016 Vehicles per Household'],
    #textposition = 'auto',
    name='2016 Vehicles per Household'
)

trace1 = go.Line(
    x =df_1['states'],
    y=df_1['percentage'],
    name='Percentage',
    xaxis='x', 
    yaxis='y2'
)

data = [trace0, trace1]
layout = go.Layout(
    title='Top 10 States With The Highest Average Number of Vehicles Per Household In 2016',
    yaxis2=dict(anchor='x', overlaying='y', side='right'),
    legend=dict(x=1,y=1)
)


fig = go.Figure(data=data, layout=layout)

cf.iplot(fig)

/anaconda3/lib/python3.7/site-packages/plotly/graph_objs/_deprecations.py:372: DeprecationWarning:

plotly.graph_objs.Line is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.scatter.Line
  - plotly.graph_objs.layout.shape.Line
  - etc.

## Task 2:
**Create a relative frequency distribution histogram from the “2016 percentage of households without vehicles” for the entire country. Comment on the shape of the distribution.**

In [10]:
df_2=uscars[['Jusidiction','2016 Households Without Vehicles']]

df_2_1=df_2.groupby('2016 Households Without Vehicles').count()

df_2_1['frequency']=df_2_1['Jusidiction']
df_2_1.drop('Jusidiction',axis=1,inplace=True)
df_2_1['relative frequency']=(df_2_1['frequency']/(df_2_1["frequency"].sum()))*100
df_2_1.head(10)

                                  frequency  relative frequency
2016 Households Without Vehicles
0.007                                     1            0.315457
0.010                                     1            0.315457
0.013                                     2            0.630915
0.014                                     2            0.630915
0.015                                     1            0.315457
0.017                                     2            0.630915
0.018                                     1            0.315457
0.020                                     2            0.630915
0.021                                     1            0.315457
0.022                                     1            0.315457

In [11]:
df_2_1.reset_index(inplace=True)
df_2_1.head(10)

trace2 = go.Histogram(
    x=df_2_1['2016 Households Without Vehicles'],
    y=df_2_1['relative frequency'],
    histnorm='probability',
    #mode='markers'
)
data=[trace2]
layout = go.Layout(
    title='Relative Frequency of 2016 Households Without Vehicles',
    yaxis=dict(title='Relative Frequency'),
    xaxis=dict(title='2016 Households Without Vehicles')
)

fig = go.Figure(data=data,layout=layout)
cf.iplot(fig)

## Task 3:
**Create a cumulative frequency line plot of the “2016 percentage of households without vehicles” for the entire country.**

In [12]:
df_2_1['cumulative frequency']=df_2_1['frequency'].cumsum()
df_2_1.set_index('2016 Households Without Vehicles',inplace=True)
df_2_1.head(10)

,frequency,relative frequency,cumulative frequency
2016 Households Without Vehicles,,,
0.007,1,0.315457,1
0.010,1,0.315457,2
0.013,2,0.630915,4
0.014,2,0.630915,6
0.015,1,0.315457,7
0.017,2,0.630915,9
0.018,1,0.315457,10
0.020,2,0.630915,12
0.021,1,0.315457,13
0.022,1,0.315457,14

In [13]:
df_2_1['cumulative frequency'].iplot(kind='line',
                                     title='Cumulative Frequency of The “2016 Percentage of Households Without Vehicles”')

## Task 4:
**Perform numerical descriptive statistics for the “2016 Vehicles per Household” for the entire country.**

In [45]:
ds=pd.DataFrame(uscars['2016 Vehicles per Household'].describe())
ds['Descriptive Statistics']=ds['2016 Vehicles per Household']
ds.drop('2016 Vehicles per Household',axis=1,inplace=True)
ds

       Descriptive Statistics
count              317.000000
mean                 1.715363
std                  0.298963
min                  0.630000
25%                  1.550000
50%                  1.720000
75%                  1.910000
max                  2.360000

In [50]:
from scipy import stats
import statistics

ds1=pd.DataFrame({'Descriptive Statistics':[np.var(uscars['2016 Vehicles per Household']),
                                 np.median(uscars['2016 Vehicles per Household']),
                                 np.cov(uscars['2016 Vehicles per Household']),
                                 #uscars['2016 Vehicles per Household'].mode(),
                                 stats.skew(uscars['2016 Vehicles per Household']),
                                 stats.kurtosis(uscars['2016 Vehicles per Household']),
                                 statistics.variance(uscars['2016 Vehicles per Household'])]},
                index=['Variance','Median','Sample Variance','Skewness','Kurtosis','Variance']
          
                                               )
ds1

                Descriptive Statistics
Variance                     0.0890968
Median                            1.72
Sample Variance     0.0893787445593579
Skewness                     -0.510263
Kurtosis                      0.598447
Variance                     0.0893787

In [51]:
uscars['2016 Vehicles per Household'].mode()

0    1.62
1    1.69
2    1.95
dtype: float64

## Task 5:
**For the “2016 percentage of households without vehicle” for the entire country, determine whether there are any outliers. Comment on the states to which the outliers belong.**

In [14]:
Q1 = uscars['2016 Households Without Vehicles'].quantile(0.25)
Q3 = uscars['2016 Households Without Vehicles'].quantile(0.75)
IQR = Q3 - Q1
print(IQR)

0.06

In [15]:
outliers_1=uscars[(uscars['2016 Households Without Vehicles']<(Q1-1.5*IQR))
                |(uscars['2016 Households Without Vehicles']>(Q3+1.5*IQR))]
                                                               
outliers_1[['Jusidiction','2016 Households Without Vehicles']].head(10)

                 Jusidiction  2016 Households Without Vehicles
21       Baltimore, Maryland                             0.289
25      Berkeley, California                             0.231
29     Boston, Massachusetts                             0.338
32   Bridgeport, Connecticut                             0.201
35         Buffalo, New York                             0.282
37  Cambridge, Massachusetts                             0.368
49         Chicago, Illinois                             0.275
51          Cincinnati, Ohio                             0.212
54           Cleveland, Ohio                             0.237
76         Detroit, Michigan                             0.247

In [16]:
outliers_1['2016 Households Without Vehicles'].count()

27

## Task 6:
**Repeat tasks 2-5 above for the “2015 percentage of households without vehicle”. Describe whether there are any similarities or dissimilarities in the distributions of the two variables that you have analyzed (the two variables are: “2016 percentage of households without vehicles” and “2015 percentage of households without vehicles”).**

**6.1 Create a relative frequency distribution histogram from the “2015 percentage of households without vehicles” for the entire country. Comment on the shape of the distribution.**

In [17]:
df_6=uscars[['Jusidiction','2015 Households Without Vehicles']]

df_6_1=df_6.groupby('2015 Households Without Vehicles').count()

df_6_1['frequency']=df_6_1['Jusidiction']
df_6_1.drop('Jusidiction',axis=1,inplace=True)
df_6_1['relative frequency']=(df_6_1['frequency']/(df_6_1["frequency"].sum()))*100

df_6_1.reset_index(inplace=True)

In [18]:
trace6 = go.Histogram(
    x=df_6_1['2015 Households Without Vehicles'],
    y=df_6_1['relative frequency'],
    histnorm='probability'
)
data=[trace6]
layout = go.Layout(
    title='Relative Frequency of 2015 Households Without Vehicles',
    yaxis=dict(title='Relative Frequency'),
    xaxis=dict(title='2015 Households Without Vehicles')
)

fig = go.Figure(data=data,layout=layout)
cf.iplot(fig)

**6.2 Create a cumulative frequency line plot of the “2015 percentage of households without vehicles” for the entire country.**

In [20]:
df_6_1['cumulative frequency']=df_6_1['frequency'].cumsum()
df_6_1.set_index('2015 Households Without Vehicles',inplace=True)
df_6_1.head(10)

,frequency,relative frequency,cumulative frequency
2015 Households Without Vehicles,,,
0.010,1,0.315457,1
0.011,1,0.315457,2
0.019,2,0.630915,4
0.022,3,0.946372,7
0.023,1,0.315457,8
0.024,3,0.946372,11
0.025,1,0.315457,12
0.026,3,0.946372,15
0.027,2,0.630915,17
0.028,3,0.946372,20

In [21]:
df_6_1['cumulative frequency'].iplot(kind='line',
                                     title='Cumulative Frequency of The “2015 Percentage of Households Without Vehicles”')

**6.3 Perform numerical descriptive statistics for the “2015 Vehicles per Household” for the entire country.**

In [64]:
ds3=pd.DataFrame(uscars['2015 Vehicles per Household'].describe())
ds3['Descriptive Statistics']=ds3['2015 Vehicles per Household']
ds3.drop('2015 Vehicles per Household',axis=1,inplace=True)
ds3

       Descriptive Statistics
count              317.000000
mean                 1.691041
std                  0.291922
min                  0.630000
25%                  1.540000
50%                  1.680000
75%                  1.880000
max                  2.390000

In [68]:
from scipy import stats
import statistics

ds4=pd.DataFrame({'Descriptive Statistics':[np.var(uscars['2015 Vehicles per Household']),
                                 np.median(uscars['2015 Vehicles per Household']),
                                 np.cov(uscars['2015 Vehicles per Household']),
                                 float(uscars['2015 Vehicles per Household'].mode()),
                                 stats.skew(uscars['2015 Vehicles per Household']),
                                 stats.kurtosis(uscars['2015 Vehicles per Household']),
                                 statistics.variance(uscars['2015 Vehicles per Household'])]},
                index=['Variance','Median','Sample Variance','Mode','Skewness','Kurtosis','Variance']
          
                                               )

ds4

                Descriptive Statistics
Variance                     0.0849494
Median                            1.68
Sample Variance    0.08521821666733218
Mode                               1.6
Skewness                     -0.501744
Kurtosis                      0.653259
Variance                     0.0852182

**6.4 For the “2015 percentage of households without vehicle” for the entire country, determine whether there are any outliers. Comment on the states to which the outliers belong.**

In [36]:
Q1 = uscars['2015 Households Without Vehicles'].quantile(0.25)
Q3 = uscars['2015 Households Without Vehicles'].quantile(0.75)
IQR = Q3 - Q1
print(IQR)

0.059000000000000004

In [37]:
outliers_2=uscars[(uscars['2015 Households Without Vehicles']<(Q1-1.5*IQR))
                |(uscars['2015 Households Without Vehicles']>(Q3+1.5*IQR))]
                                                               
outliers_2[['Jusidiction','2015 Households Without Vehicles']].head(10)

                 Jusidiction  2015 Households Without Vehicles
21       Baltimore, Maryland                             0.307
29     Boston, Massachusetts                             0.354
32   Bridgeport, Connecticut                             0.221
35         Buffalo, New York                             0.300
37  Cambridge, Massachusetts                             0.309
49         Chicago, Illinois                             0.265
54           Cleveland, Ohio                             0.235
72              Dayton, Ohio                             0.222
76         Detroit, Michigan                             0.253
84     Elizabeth, New Jersey                             0.283

In [38]:
outliers_2[['Jusidiction','2015 Households Without Vehicles']].count()

Jusidiction                         26
2015 Households Without Vehicles    26
dtype: int64

## Task 7:
**Create a table that shows the average number of vehicles per household by state in 2016 (organize the table by states in alphabetic order). Next, create a same table for 2015, and create a scatter plot of the average number of vehicles per household by state in 2016 versus that of 2015. Use the scatter plot to describe whether there exists a correlation between the two quantities above. Interpret this correlation in words.**

**1.the average number of vehicles per household by state in 2016**

In [39]:
df=uscars[['Jusidiction','2016 Vehicles per Household']]
df['states']=df['Jusidiction'].apply(lambda s:s.split(',')[-1])

ave_2016=df.groupby('states').mean().sort_values(by='states')
ave_2016.head(10)

                       2016 Vehicles per Household
states
 Alabama                                  1.612500
 Alaska                                   1.950000
 Arizona                                  1.781000
 Arkansas                                 1.580000
 California                               1.960667
 Colorado                                 1.895385
 Connecticut                              1.292000
 District of Columbia                     0.860000
 Florida                                  1.629600
 Georgia                                  1.560000

**2.the average number of vehicles per household by state in 2015**

In [40]:
df=uscars[['Jusidiction','2015 Vehicles per Household']]
df['states']=df['Jusidiction'].apply(lambda s:s.split(',')[-1])

ave_2015=df.groupby('states').mean().sort_values(by='states')
ave_2015.head(10)

                       2015 Vehicles per Household
states
 Alabama                                  1.592500
 Alaska                                   1.840000
 Arizona                                  1.730000
 Arkansas                                 1.590000
 California                               1.921467
 Colorado                                 1.876154
 Connecticut                              1.282000
 District of Columbia                     0.890000
 Florida                                  1.611600
 Georgia                                  1.514286

**3.scatter plot (2016 vs 2015)**

In [41]:
ave=pd.merge(ave_2015,ave_2016,on='states',how='inner').sort_values(by='states')
ave.head(10)

,2015 Vehicles per Household,2016 Vehicles per Household
states,,
Alabama,1.592500,1.612500
Alaska,1.840000,1.950000
Arizona,1.730000,1.781000
Arkansas,1.590000,1.580000
California,1.921467,1.960667
Colorado,1.876154,1.895385
Connecticut,1.282000,1.292000
District of Columbia,0.890000,0.860000
Florida,1.611600,1.629600
Georgia,1.514286,1.560000

In [42]:
trace6 = go.Scatter(
    x=ave['2015 Vehicles per Household'],
    y=ave['2016 Vehicles per Household'],
    mode='markers'
)
data=[trace6]
layout = go.Layout(
    title='Correlation Between 2016 and 2015 in Average Number Of Vehicles per Household by State',
    yaxis=dict(title='2016 Vehicles per Household'),
    xaxis=dict(title='2015 Vehicles per Household')
)

fig = go.Figure(data=data,layout=layout)
cf.iplot(fig)